### ISSUE TITLE
cannot locate the 签到领奖 button

### ISSUE THREAD

**Issue by one-piece-of-ai** [CryoliteZ/1point3auto#1]
driver.find_element_by_xpath("//div[@id='um']/p[2]/a[3]/font").click()

Exception has occurred: NoSuchElementException
Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[@id='um']/p[2]/a[3]/font"}

**Comment by alvinbhou** [comment]
Hey zkfairytale,
  Thanks for the bug report. Could you tell me how did you encounter this exception? I supposed I have already added some [error handling ](https://github.com/CryoliteZ/1point3auto/blob/3db1465ac2c50eb5aa36ecb455b58198073f49d4/main.py#L43). This error may happen if a user has already gotten his daily award. The correct message you should see is `Couldn't access daily reward` on line 44.

**Comment by one-piece-of-ai** [comment]
Hi thanks for your reply. The bug can be triggered if the user doesn't have a button for "自由马甲". I think we can just retry using a updated index to auto fix the bug.
![image](https://user-images.githubusercontent.com/5402298/74388383-26472100-4db0-11ea-834f-bb856b18ef77.png)
![image](https://user-images.githubusercontent.com/5402298/74388427-3c54e180-4db0-11ea-8836-f0573e70f141.png)

**Comment by one-piece-of-ai** [comment]
i sent out a PR for the change. It worked in my case
https://github.com/CryoliteZ/1point3auto/pull/2/files

**Comment by alvinbhou** [comment]
Hi, nice catch! I did not realized some users does not have a button for "自由马甲". I changed the code ([line 40](https://github.com/CryoliteZ/1point3auto/blob/3db1465ac2c50eb5aa36ecb455b58198073f49d4/main.py#L40))  and tested the following code which should work

```python
# on line 40
driver.find_element_by_xpath("//font[text()='签到领奖!']").click()
```

This way the method is more general and it should work for users with or without "自由马甲". Would you please make another commit to the PR changing this line of code? I'll then merge it.

**Comment by one-piece-of-ai** [comment]
great suggestion!
