### ISSUE TITLE
Script not working

### ISSUE THREAD

**Issue by moonorblue** [CryoliteZ/1point3auto#3]
I just found the script was not working after June, could you help with it?
Thank you

**Comment by alvinbhou** [comment]
Hi! Is your problem resolved? I found that the script is not working due to the new CAPTCHA they added to the site. Sadly there are currently no workarounds (unless I use some deep learning libraries...). I'll keep you updated if I find out a solution.

**Comment by moonorblue** [comment]
Thank you for the reply, I was looking for workarounds too. I closed the issue because I should have debug myself first, not just asking for help haha. Anyway, I would keep an eye on it, thank you :)
